### ISSUE TITLE
error printed by jxlinfo

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#699]
[jxl_info.zip](https://github.com/libjxl/libjxl/files/7303233/jxl_info.zip) contains **bucuresti2.jxl** file.

It was encoded via following command:

`cjxl 10921852336_28ebe2249c_o.jpg bucuresti2.jxl -p --centerfirst -d 10 --num_threads=2 --strip -e 5`

When I use **jxlinfo**, I get some error:
```
 jxlinfo bucuresti2.jxl
dimensions: 10916x9985
have_container: 0
uses_original_profile: 0
bits_per_sample: 8
have_preview: 0
have_animation: 0
orientation: 1 (Normal)
num_color_channels: 3
num_extra_channels: 0
color profile:
  format: JPEG XL encoded color profile
  color_space: 0 (RGB color)
  white_point: 1 (D65)
  primaries: 1 (sRGB)
  transfer_function: 13 (sRGB)
  rendering_intent: 1 (Relative)
frame:
  still frame, unnamed
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/passes_state.cc:55: JXL_FAILURE: kUseDcFrame specified for dc_level 0, but no frame was decoded with level 1
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/dec_frame.cc:289: JXL_RETURN_IF_ERROR code=1: InitializePassesSharedState(frame_header_, &dec_state_->shared_storage)
Decoder error
```
